### ISSUE TITLE
Black map layer with v0.9.9

### ISSUE THREAD

**Issue by daishimatt** [SDoehren/always-centred#8]
Hi,

I'm not sure if this is just me, or a 0.9.9 issue for always-centred.  When I use this (on its own, no other modules) the map layer will no longer load, I just get a black screen.  Its almost like a new layer is being added over the screen which is stopping anything else working.  This isn't the only module I have that seems to have this issue unfortunately.

**Comment by SDoehren** [comment]
Hi,

Thanks for raising the issue.  

Officially I dont support V9 for Always Centred yet and the V9 version is being listed as a early 2022 fix.

Fortunately one of my bigger modules had the same issue and the issue was with something I do in both modules.  
So, assuming it is the same issue, I'm hoping it will be an extremely quick fix later this week.

**Comment by SDoehren** [comment]
Issue resolved in V0005
